FROM node:18.12.1 AS builder

WORKDIR /app

COPY . ./

RUN npm i
RUN npm run build

FROM node:18.12.1

RUN npm i -g serve
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

EXPOSE 443

CMD [ "npm","run","start:prod" ]