version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: supertokens_user
      MYSQL_PASSWORD: somePassword
      MYSQL_DATABASE: supertokens
    ports:
      - 3306:3306
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-mysql:4.2
    depends_on:
      - db
    ports:
      - 3567:3567
    environment:
      MYSQL_CONNECTION_URI: mysql://supertokens_user:somePassword@db:3306/supertokens
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    depends_on:
      - db
      - supertokens
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "80:80"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: curl -fs http://localhost:80/health || exit 1
      interval: 1h
      timeout: 5s
      retries: 3

  client:
    depends_on: 
      - server
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge